Create sequences_miray_cengil.py
canbula/ParallelProgramming pull request #499
Opened 2024-10-07 21:21 UTC by miraycengil

## Describe your changes

## Checklist
- [ ] I have read the [CONTRIBUTING]
- [ ] I have performed a self-review of my own code
- [ ] I have run the code locally and it works as expected
- [ ] I have commented my code, particularly in hard-to-understand areas

## Screenshots (if appropriate)

2024-10-12 21:43 UTC, canbula requested changes
See the test results.

2024-10-12 21:43 UTC, canbula commented on Week03/sequences_miray_cengil.py
> +    new_dict = defaultdict(list)
You have an undefined name in this line.

2024-10-26 12:09 UTC, canbula requested changes
I don't want you to import any modules.

2024-11-03 23:54 UTC, miraycengil commented
Ok, sorry I used unnecessary modules in all my codes, I removed them all. I hope it's correct this time.

2024-11-22 18:12 UTC, canbula approved these changes
👍

2024-11-22 18:12 UTC, merged